### ISSUE TITLE
Solving saves the image if capture is paused

### ISSUE THREAD

**Issue by gloushkov** [indigo-astronomy/indigo_imager#1]
Solving a frame saves the preview image file in the directory where a current capture sessions is running.

1. Start a capture batch
2. Pause the batch
3. Solve a frame

Observe image saved as part of the capture sequence

**Comment by rumengb** [comment]
Thank you for the report I will look at it as soon as I can.

**Comment by rumengb** [comment]
Fixed with commit 2deaff6719444e5947809fa9520cb0c593056fa1
