### ISSUE TITLE
Focuser absolute position movement is broken on 0.16-2

### ISSUE THREAD

**Issue by Paolo97Gll** [indigo-astronomy/indigo_imager#10]
Focuser absolute position movement is broken on AIN imager version 0.16-2 but working on version 0.16-1 and with the webpage (using INDIGO 2.0-202), using a custom driver (we don't have any other focuser to be tested).

On driver side, the `FOCUSER_POSITION_PROPERTY` change request arrives, but the variable `FOCUSER_POSITION_ITEM->number.target` is not updated with the inserted value, so the movement does not start.

Instead, the relative movement is ok.

**Comment by rumengb** [comment]
Fixed with commit 421e31a517af414c6e95eca2de13adfe9aa38cbb it will come as a fix in the next release
