### ISSUE TITLE
"localtime_r" missing in "viewerwindow.cpp" when building on windows with MinGW

### ISSUE THREAD

**Issue by thx8411** [indigo-astronomy/indigo_imager#13]
Hello,

When building on Windows 10 with MinGW I get :

`
../../ain_viewer_src/viewerwindow.cpp: In member function 'void ViewerWindow::on_image_info_act()':
../../ain_viewer_src/viewerwindow.cpp:426:33: error: 'localtime_r' was not declared in this scope; did you mean 'localtime_s'?
  426 |                                 localtime_r(&image_info.timestamp, &tm);
      |                                 ^~~~~~~~~~~
      |                                 localtime_s
`

Avoided by adding : 

`
#if defined(__MINGW32__) || defined(__MINGW64__)
#define localtime_r(T,Tm) (localtime_s(Tm,T) ? NULL : Tm)
#endif
`

at the beginning of "viewerwindow.cpp".

Not very clean. Not sure if it's safe yet, but it works.

Best regards,

Thx8411

**Comment by rumengb** [comment]
I am using MinGW which comes with the QT 5, to build Ain and it works fine.

**Comment by thx8411** [comment]
Hello,

Thanks.

Right, it was related to MinGW 11.2.
I Switched to MinGW 8.1.

No more issues
