### ISSUE TITLE
Unable to choose ASTAP Agent

### ISSUE THREAD

**Issue by timsurber** [indigo-astronomy/indigo_imager#17]
I prefer to use ASTAP over Astrometry because of the better performance when blind solving on a weak CPU.

I have activated the ASTAP Agent, but I can only choose Astrometry.
![no_astap_agent](https://github.com/indigo-astronomy/indigo_imager/assets/138802321/8fd698ff-406d-4197-8798-d612d59d3268)

**Comment by rumengb** [comment]
ASTAP Agent is deprecated, as Han the creator of ASTAP suddenly decided to
remove all the changes he made to ASTAP to integrate it with INDIGO without
any notification. So INDIGO works with one particular ancient version of
astap which is no longer supported. Therefore Ain does not load and does
work with ASTAP. However, if you tune the parameters correctly Astrometry
on Raspberry Pi 4 can solve frames for several seconds. My field is 2x3
degrees and I have it solved for 4-5s.

Please look at:
https://github.com/indigo-astronomy/indigo/blob/master/indigo_docs/PLATE_SOLVING.md

**Comment by timsurber** [comment]
Astrometry does not work correctly for me. Try blindsolving the attached picture, no problem on ASTAP does not solve on Astrometry.
![stars3](https://github.com/indigo-astronomy/indigo_imager/assets/138802321/2a620238-d459-4465-b0f6-9a77848fd96c)

Would you accept patches to make ASTAP work again?
I think it would be great for the community to have options.

**Comment by rumengb** [comment]
This image is blind solved in 3.1s on Raspberry Pi with astrometry and RPi is pretty slow compared to a PC.
See the image upload and solved timestamps on the screenshot:
![Screenshot from 2024-03-20 23-07-30](https://github.com/indigo-astronomy/indigo_imager/assets/20597893/38fc01d2-f340-4953-86e3-92e90e998689)

so you must be doing something wrong :)

**Comment by timsurber** [comment]
You are right, I was missing one index file. On my hardware (Allwinner H618) it solves in around 15 seconds, which is okay I guess.
Maybe I will look into further optimizations sometime.

Thank you
