### ISSUE TITLE
Feature Request - Crosshairs on Capture page

### ISSUE THREAD

**Issue by astroman68** [indigo-astronomy/indigo_imager#2]
If possible, could you add a simple set of cross-hairs (maybe toggle off/on) in center of image on capture tab so drift can be more easily monitored during imaging? Thanks for your consideration.

**Comment by rumengb** [comment]
It can be done but I do not understand: Why do you need to monitor drift when you capture frames?
Can you please be more specific? Like the one in the guider tab? Also can you give me an example use case for that?

**Comment by astroman68** [comment]
Hi Rumen, sure...

With my setup, depending on where I am imaging in the sky, I get different amounts of object drift over long periods of time. Even while guiding (probably due to flexure, but just guessing). I use a C8 with Hyperstar (F1.9 390mm FL) and mostly take many sub 1min exposures (light polluted area). Guiding is usually good with 1" to sub 1" guiding, although I probably don't even need to guide. All that said, sometimes I can image for 2 hours or so and only see about 25px of drift ( not enough to adjust with 1931x1451 image), but other times I may get 100+ px drift in an hour. If I let it drift to far without making an adjustment, I end up having to crop the picture quite a bit to get rid of the areas along the edge that have poor data. 

So, up to this point when using other software packages that had cross-hairs, I would turn it on and monitor the drift using either the center of the object (like M31 or M42) or some star somewhere in the middle. Then I would check it every now and then and if it drifts off by some amount, let say 50px, I would pause the session, bump the scope back over (or use solve and center) and continue the session. In ain_imager, I can do it with the mouse, find the center using the px reading in the top right, but that is a little tedious and it would be nice if I could just look at the preview with cross-hairs and immediately see the amount I have drifted. Another use case I have used them for is when doing a solve and center to quickly see if the solve/center routine was working well, or if, for whatever the reason, I was centering the view manually. Its just easier when looking at the screen from different angles (above when standing, from left or right when leaning) to see when something is centered.

Thanks again, hope this wasn't to long winded -- Stephen

**Comment by rumengb** [comment]
Hi Stephen, I can do that. Can you show me some software that has it so that I can see how it works?

**Comment by astroman68** [comment]
Sure can, when I can get to my imaging PC's later today. In the mean time I have attached a couple of mock ups that basically show what I have seen in other packages. Also, if you have access to KStars/Ekos, you can look on the fits viewer that updates after each exposure that actually has both cross-hairs and a grid, if I remember right ( I personally haven't found the grid useful, but I suppose others might find it helps to compare star roundness around the image). I've used probably 5 different packages and they are all basically the same. Some just have a cross, some can toggle an X shape, some with a small circle in the middle, some with a couple circles, etc. For me, In the end, just knowing where the center is is good enough, even if it were just a red 5x5px dot ;-)

![ain_imager-example-lines](https://user-images.githubusercontent.com/83990821/139901469-cca5bb25-2654-4b16-b57d-6e022f0892fa.png)
![ain_imager-example-circle](https://user-images.githubusercontent.com/83990821/139901556-db6c5594-dd35-4229-ba54-8b904a6610f8.png)
.

**Comment by rumengb** [comment]
Got it! Will add it in the TODO! Do you need it to be in the center only or you want to move it?

**Comment by astroman68** [comment]
Center only is fine with me. Can't think of a reason why I would need to move it.

**Comment by astroman68** [comment]
Examples I promised in case they are helpful. These are from Ekos, Sequence Generator Pro and SharpCap
![ekos-cross-hair-example](https://user-images.githubusercontent.com/83990821/139960179-97465777-6d47-41dc-a6b1-de3b73f556bf.png)
![SharpCap-cross-hair-example](https://user-images.githubusercontent.com/83990821/139960202-5dd02d7c-2493-4508-9cb9-1894e1da4d6b.JPG)
tent.com/83990821/139960190-7ba4236b-d8d3-48c9-af59-dfa9735fafa8.JPG)
![SGP-cross-hair-example](https://user-images.githubusercontent.com/83990821/139960462-6b035ec7-8db6-442e-aa7f-ae954792d6a0.JPG)
.

**Comment by rumengb** [comment]
Fixed with commit 0d27a7fb703436c1c624fbfcd300a4225a85cc4f

Will be publicly available with the next release.

![image](https://user-images.githubusercontent.com/20597893/139966861-b58d6d7a-f7b6-4e7f-9b98-3b3f4cfa69c3.png)

**Comment by astroman68** [comment]
Awesome! Thanks again.

**Comment by rumengb** [comment]
It is toggled by "Settings->Show image center" and will be shown everywhere except Focus and Guide tabs. I think it makes sense for Telescope, Solver and Capture but not for Focus. Actually Guide uses the same crosshairs to show the reference position and is shown only while guiding and it is not in the center.
