### ISSUE TITLE
Compile 1.7-0 in Linux encounter error: 'AGENT_IMAGER_SELECTION_STAR_COUNT_ITEM_NAME' was not declared in this scope

### ISSUE THREAD

**Issue by chtay** [indigo-astronomy/indigo_imager#37]
Compile indigo_imager v1.7-0 in openSUSE Leap 15.6 encounter error. For v1.6-0, with the same compile instruction give, it can compile succesfully.

Here is the possible error message it encounter during compiling (make):

changeproperty.cpp:289:83: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  p = properties.get(selected_imager_agent, FILTER_RELATED_AGENT_LIST_PROPERTY_NAME);
                                                                                   ^
changeproperty.cpp: In member function 'void ImagerWindow::change_agent_star_count(const char*) const':
changeproperty.cpp:409:3: error: 'AGENT_IMAGER_SELECTION_STAR_COUNT_ITEM_NAME' was not declared in this scope
   AGENT_IMAGER_SELECTION_STAR_COUNT_ITEM_NAME
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
changeproperty.cpp:409:3: note: suggested alternative: 'AGENT_GUIDER_SELECTION_STAR_COUNT_ITEM_NAME'
   AGENT_IMAGER_SELECTION_STAR_COUNT_ITEM_NAME
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   AGENT_GUIDER_SELECTION_STAR_COUNT_ITEM_NAME
changeproperty.cpp: In member function 'void ImagerWindow::clear_imager_agent_star_selection(const char*) const':
changeproperty.cpp:431:86: error: 'AGENT_GUIDER_CLEAR_SELECTION_ITEM_NAME' was not declared in this scope
   indigo_change_switch_property_1(nullptr, agent, AGENT_START_PROCESS_PROPERTY_NAME, AGENT_GUIDER_CLEAR_SELECTION_ITEM_NAME, true);
                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
changeproperty.cpp:431:86: note: suggested alternative: 'AGENT_GUIDER_SELECTION_Y_ITEM_NAME'
   indigo_change_switch_property_1(nullptr, agent, AGENT_START_PROCESS_PROPERTY_NAME, AGENT_GUIDER_CLEAR_SELECTION_ITEM_NAME, true);
                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                      AGENT_GUIDER_SELECTION_Y_ITEM_NAME
changeproperty.cpp: In member function 'void ImagerWindow::clear_guider_agent_star_selection(const char*) const':
changeproperty.cpp:444:86: error: 'AGENT_GUIDER_CLEAR_SELECTION_ITEM_NAME' was not declared in this scope
   indigo_change_switch_property_1(nullptr, agent, AGENT_START_PROCESS_PROPERTY_NAME, AGENT_GUIDER_CLEAR_SELECTION_ITEM_NAME, true);
                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
changeproperty.cpp:444:86: note: suggested alternative: 'AGENT_GUIDER_SELECTION_Y_ITEM_NAME'
   indigo_change_switch_property_1(nullptr, agent, AGENT_START_PROCESS_PROPERTY_NAME, AGENT_GUIDER_CLEAR_SELECTION_ITEM_NAME, true);
                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                      AGENT_GUIDER_SELECTION_Y_ITEM_NAME
changeproperty.cpp:451:89: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   indigo_property *p = properties.get((char*)agent, AGENT_GUIDER_SELECTION_PROPERTY_NAME);
                                                                                         ^
changeproperty.cpp:453:85: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   indigo_item *item = indigo_get_item(p, AGENT_GUIDER_SELECTION_STAR_COUNT_ITEM_NAME);
                                                                                     ^

**Comment by chtay** [comment]
I think the reason it failed to compile successfully is due to I only have indigo-server 2.10-290 (developer files) installed. It can compile for v1.6-0 but not v1.7

**Comment by rumengb** [comment]
There are new features in Indigo 2.0-296 that are used by Ain 1.7 so you need to update Indigo.
