### ISSUE TITLE
specifying IP for a server causes weird server name display

### ISSUE THREAD

**Issue by ckuethe** [indigo-astronomy/indigo_imager#4]
Just like indigo-astronomy/indigo_control_panel#4
![Screenshot_2021-11-07_14-51-37](https://user-images.githubusercontent.com/1131751/140664857-27a97b75-5b57-4c58-b0dc-5a0c8f0fc2eb.png)

**Comment by rumengb** [comment]
fixed with commit: 7895d7771dadcd233553a7ce0b85e0ee821e03f4
will be available in the next release
