### ISSUE TITLE
Exposure length field.

### ISSUE THREAD

**Issue by ckuethe** [indigo-astronomy/indigo_imager#5]
Is the exposure field really an integer, because that's what the tooltip implies? If it's a fraction, the tooltip is wrong. Also, it won't let me enter a small number like 0.000032 or "3.2e-5"

![Screenshot_2021-11-13_20-46-50](https://user-images.githubusercontent.com/1131751/141668657-188d695b-2918-472e-b579-e6a26bde15c0.png)

**Comment by rumengb** [comment]
Hi Chris The tool tip is OK. Step 1 means that if you press Up or Down arrow it will increase or decrease the exposure time by 1s. However as it is not you can enter exposure time with 0.01s accuracy. Ain is not optimized for planetary imaging yet, which means that exposures of 0.000032 do not make much sense. The only scenario that I can think of is taking bias frames. But in this case you should select "Bias" and the driver will set the minimum exposure the camera is capable of.
I can increase the resolution of the SpinBox but I do not see any reason for that. 
Can you please explain why do you need to enter 3.2e-5? First why this resolution? And second why exponential notation?

**Comment by ckuethe** [comment]
As you said, for bias frames. It wasn't clear that the light/dark/whatever selector did anything other than change the file name.

Part of the reason I thought I might be able to use scientific notation is because I can do so in the control panel.

**Comment by rumengb** [comment]
They do :)
Bias - sets the shortest exposure and does not open the shutter (if available). Dark - does not open the shutter (if available)
etc... 

Scientific notation does not make much sense here in Ain. Control panel is a low level tool used for configuration by the users and it exposes all capabilities (properties) of the device, but it has a "dark" side: it is being used for debugging by the developers that is why it allows you to enter any possible value wrong or right and relays solely on the server to perform the data validity check.

I am closing this thicket :)...
