### ISSUE TITLE
Streaming preview with histogram?

### ISSUE THREAD

**Issue by ckuethe** [indigo-astronomy/indigo_imager#6]
In the web imager I can set preview into a streaming/continuous mode with an optional histogram. I don't seem to have that option in the imager

trace log, in case it's helpful https://gist.github.com/6e0bb6b55f8e0e343fc1b7b5c73622df

![Screenshot_2021-11-17_11-10-06](https://user-images.githubusercontent.com/1131751/142267001-3db6774e-7a33-40d7-8036-bc648e885fec.png)

**Comment by rumengb** [comment]
No streaming in the Ain Imager. Streaming is needed for planetary, and Ain is not yet optimized for planetary. Once Ain is feature complete for deep sky I will start implementing the planetary features.

What comes to histogram. I do not find it of any value for deep sky astro-photography... histograms of all images look pretty much the same. One spike extreme left and that it. It may be somewhat useful for the image preview stretching and it was previously used by Ain internally for that reason, but the histogram was never displayed. Some time ago Ain started to use a lot better preview algorithm (the one used by PixInsight for STF) and histogram became of no use at all... However showing histogram is in the TODO but not a top priority.

**Comment by ckuethe** [comment]
My use case for streaming preview is to get my focusing right. I don't have a motorized focuser so I'm gently nudging around my focuser around while looking at the spikes from my Bahtinov mask. Histogram is the same for me... nudge my settings around to get set up for the night, then go back inside.

**Comment by rumengb** [comment]
You do not need it :) There is a manual focus mode in INDIGO which helps you to find best focus without bachtinov :)

Use Focus tab -> Settings, select "Focus mode: Manual":
![image](https://user-images.githubusercontent.com/20597893/142286117-d5057e48-9b41-442a-b981-6ae812130d5f.png)

Then change sub tab to "Statistics", select a star by right-clicking on the image (or leave indigo to choose a star for you) and press "Focus". Ain will start looping exposures and show you some statistics in a graph:
![image](https://user-images.githubusercontent.com/20597893/142286842-3edd4de7-ae70-43ad-9e90-4a99895ed0a6.png)
 If you use Peak / HFD focus estimator the min in the graph is the best focus.
(if you use bachtinov the stats will not be accurate, use either bachtinov either stats but never both)
